### ISSUE TITLE
ClassAnalysisDescCompleter uses ASM6 so it can't read newer Minecraft jars

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/mapping-io#35]
More specifically:
```
java.lang.UnsupportedOperationException: NestHost requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:174)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:586)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at net.fabricmc.mappingio.tree.ClassAnalysisDescCompleter.processClass(ClassAnalysisDescCompleter.java:138)
	at net.fabricmc.mappingio.tree.ClassAnalysisDescCompleter.processFile(ClassAnalysisDescCompleter.java:121)
	at net.fabricmc.mappingio.tree.ClassAnalysisDescCompleter.access$000(ClassAnalysisDescCompleter.java:45)
	at net.fabricmc.mappingio.tree.ClassAnalysisDescCompleter$DirVisitor.visitFile(ClassAnalysisDescCompleter.java:63)
	at net.fabricmc.mappingio.tree.ClassAnalysisDescCompleter$DirVisitor.visitFile(ClassAnalysisDescCompleter.java:56)
	at net.fabricmc.mappingio.tree.ClassAnalysisDescCompleter.processFile(ClassAnalysisDescCompleter.java:99)
	at net.fabricmc.mappingio.tree.ClassAnalysisDescCompleter.process(ClassAnalysisDescCompleter.java:52)
```

**Comment by modmuss50** [comment]
Seems to use ASM9 here: https://github.com/FabricMC/mapping-io/blob/master/src/main/java/net/fabricmc/mappingio/tree/ClassAnalysisDescCompleter.java#L143 ?

Im not a massive fan of how it can be overriden by the system prop, I think it would be best to take this from the `processClass` methods.

**Comment by Juuxel** [comment]
Oh, ignore this issue then. Loom has a very outdated version:

https://github.com/FabricMC/fabric-loom/blob/d1f35d42218d0710ca640e6f8bef31b7232a9304/build.gradle#L84
