### ISSUE TITLE
'queuePendingMember' causes NPE

### ISSUE THREAD

**Issue by fxshlein** [FabricMC/mapping-io#68]
There is this bit of code here, which constructs `FieldEntry` and `MethodEntry` objects with the source name set to `null`:
https://github.com/FabricMC/mapping-io/blob/a3018992c00a33fa55f1901ce94c4edaa4a63103/src/main/java/net/fabricmc/mappingio/tree/MemoryMappingTree.java#L479-L483

I think this always causes a null pointer exception, because the parent constructor uses it to construct a key:
https://github.com/FabricMC/mapping-io/blob/a3018992c00a33fa55f1901ce94c4edaa4a63103/src/main/java/net/fabricmc/mappingio/tree/MemoryMappingTree.java#L1122

And the constructor of the key in turn calls `.hashCode()` on the name without checking for null:
https://github.com/FabricMC/mapping-io/blob/a3018992c00a33fa55f1901ce94c4edaa4a63103/src/main/java/net/fabricmc/mappingio/tree/MemoryMappingTree.java#L1680-L1684

I suppose, since a key without the name being present probably makes little sense, it would make sense to lazily compute the key as soon as the entry is no longer pending?

Stack trace of the exception:

```stacktrace
Caused by: java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "name" is null
	at net.fabricmc.mappingio.tree.MemoryMappingTree$MemberKey.<init>(MemoryMappingTree.java:1683)
	at net.fabricmc.mappingio.tree.MemoryMappingTree$MemberEntry.<init>(MemoryMappingTree.java:1122)
	at net.fabricmc.mappingio.tree.MemoryMappingTree$MethodEntry.<init>(MemoryMappingTree.java:1217)
	at net.fabricmc.mappingio.tree.MemoryMappingTree.queuePendingMember(MemoryMappingTree.java:482)
	at net.fabricmc.mappingio.tree.MemoryMappingTree.visitMethod(MemoryMappingTree.java:459)
	at net.fabricmc.mappingio.adapter.ForwardingMappingVisitor.visitMethod(ForwardingMappingVisitor.java:77)
	at net.fabricmc.mappingio.format.tiny.Tiny2FileReader.readClass(Tiny2FileReader.java:149)
	at net.fabricmc.mappingio.format.tiny.Tiny2FileReader.read(Tiny2FileReader.java:116)
	at net.fabricmc.mappingio.format.tiny.Tiny2FileReader.read(Tiny2FileReader.java:55)
	at net.fabricmc.mappingio.MappingReader.read(MappingReader.java:186)
```

**Comment by NebelNidas** [comment]
It's not a particularly urgent issue, since the use case this was designed to cover wasn't supported previously either and would've crashed anyway.

**Comment by fxshlein** [comment]
Yeah I thought as much haha, just wanted to mentioned it. I ran into it because I was trying to hook up mappings wrongly, which "triggered" this feature, after I did it right it worked perfectly.
